server:
  port: 8081
  servlet:
    context-path: /services/be/user-service

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

doc:
  api:
    path: /doc/api
    title: User API
    description: Documentation for the User API
    version: 1.0.0

file:
  path-save: "media"


